# Nombre del workflow
name: Actividad GitHub Actions

on:

  # Se ejecuta cuando hay un push a la rama main
  push:
    branches: [ "main" ]

  # Se ejecuta cuando hay un pull request hacia main
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# se definen los jobs del workflow
jobs:


  build:

    # Le dice en que sistema operativo se ejecuta
    runs-on: ubuntu-latest

    # Variables de entorno y secretos
    env:
      plataforma: aws
      region: america
      cuenta: desarrollador
      USER_NAME: ${{ secrets.NOMBRE_USUARIO }}
      USER_PASS: ${{ secrets.password }}

    # Lista de pasos 
    steps:


      - uses: actions/checkout@v4

      # muestra un mensaje
      - name: Mostrar mensaje
        run: echo "Hola Mundo"

      # Muestra las variables de entorno
      - name: Probando las variables de entorno
        run: |
          echo "Plataforma de despliegue: ${{ env.plataforma }}"
          echo "Región asignada: ${{ env.region }}"
          echo "Entorno de cuenta: ${{ env.cuenta }}"

      # Muestra información del evento que ejecuto el workflow en formato Json
      - name: Debug del payload completo
        run: echo "${{ toJSON(github.event) }}"

      # Muestra metadatos del repositorio
      - name: Mostrar metadatos Básicos
        run: |
          echo "Usuario ejecutor: ${{ github.actor }}"
          echo "Repositorio activo: ${{ github.repository }}"

      # valida que existan el usuario y la contraseña
      - name: Validación de Credenciales
        if: env.USER_NAME != '' && env.USER_PASS != ''
        run: |
          echo "Estado: Credenciales de autenticación detectadas. Procediendo..."

      # Muestra variable global
      - name: Referencia a Variable Global
        run: |
          echo "Versión del proyecto: ${{ vars.PROJECT_VERSION }}"

      # Ejecuta varios comandos de prueba
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
